stages:
  - build
  - publish

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: "m1kky8/osi-bot"
  IMAGE_TAG: "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
  LATEST_TAG: "$DOCKER_IMAGE:latest"

default:
  image: docker:latest
  tags:
    - sloboda

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  services:
    - docker:dind
  script:
    - echo "Pulling cached images (if they exist)..."
    - docker pull "$IMAGE_TAG" || true
    - docker pull "$LATEST_TAG" || true
    - echo "Building Docker image with cache..."
    - >
      docker build
      --cache-from="$IMAGE_TAG"
      --cache-from="$LATEST_TAG"
      --build-arg BUILDKIT_INLINE_CACHE=1
      -t "$IMAGE_TAG" -t "$LATEST_TAG" .
    - docker push "$IMAGE_TAG"
    - docker push "$LATEST_TAG"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    DOCKER_USERNAME: "m1kky8"
    DOCKER_PASSWORD: "$DOCKER_PASS" # Set this in GitLab CI/CD variables
